### ISSUE TITLE
2.0.3 version not working for me

### ISSUE THREAD

**Issue by vforv** [hemerajs/hemera-testsuite#10]
here is my test:

> import * as lab from 'lab';
> const L = exports.lab = lab.script();
> 
> const Hemera = require('nats-hemera')
> const Nats = require('hemera-testsuite/nats')
> 
> const nats = new Nats()
> const hemera = new Hemera(nats)
> 
> 
> L.experiment('Basic test', () => {
> 
>     L.test('Math', (done) => {
> 
>         hemera.ready(function () {
>             hemera.add(
>                 {
>                     topic: 'math',
>                     cmd: 'add'
>                 },
>                 (req: any) => req.a + req.b
>             )
>             hemera.act(`topic:math,cmd:add,a:1,b:2`, (err: any, resp: any) => {
>                 console.log(err, resp)
>                 done();
>             })
>         })
>     });
> 
> });
> 

I am getting Timeout error

**Comment by StarpTech** [comment]
Hi @vforv the same example you can find here https://github.com/hemerajs/hemera-testsuite/blob/master/test/nats.spec.js#L9 and all tests are green. Do you use the latest version of hemera, hemera-testsuite?

**Comment by StarpTech** [comment]
Please try again with hemera-testsuite 2.0.5
