### ISSUE TITLE
Testing with real NATS Server connection

### ISSUE THREAD

**Issue by vforv** [hemerajs/hemera-testsuite#13]
Is it possible to connect to nats server even if it is not installed in localhost? 
If not that would be nice to have...

Ex.

```
var PORT = 6242
var authUrl = 'nats://REMOTE_IP:' + PORT

const nats = require('nats').connect(authUrl)
```

If we don't have this it will use more space if we have for each service nats server...

**Comment by StarpTech** [comment]
This is not possible we rely on a complex messaging system and hemera is just a consumer. You can do simple in-memory test with the tools here https://github.com/hemerajs/hemera-testsuite/blob/master/test/nats.spec.js
