### ISSUE TITLE
How to stub functions inside actions?

### ISSUE THREAD

**Issue by vforv** [hemerajs/hemera-testsuite#7]
Hi,

I added bcrypt module in existing repo:

https://github.com/vforv/hemera-error

And error will occure again inside the second action... Problem is because the second action receive hash from bcrypt function...

So how can I stub bcrypt module and if is it possible to read values of properties from actions?
Also is possible to action receive input dynamically from bcrypt?

**Comment by StarpTech** [comment]
Hi @vforv what's the issue about? Please describe the error in detail.

What do you expect?
What is the log?
Hemera Version,
Node Version,
Do you using transpiler?

**Comment by vforv** [comment]
Hi @StarpTech ,

The code should run until the end but I get the timeout error. The last stubbed action never run because hash that I get from bcrypt function.

For all other details, you can find in repo:
https://github.com/vforv/hemera-error

**Comment by StarpTech** [comment]
@vforv please clean up your code and reduce it to the bare of minimum. Attach always a log trace.

> The last stubbed action never run because hash that I get from bcrypt function.
That makes no sense to me

**Comment by vforv** [comment]
Please check repo again, I added test console log in README.

**Comment by StarpTech** [comment]
Look at https://github.com/hemerajs/hemera-testsuite/pull/9
